eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka

server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user
            uri: lb://USER
            predicates:
              - Path=/users/**
          - id: item
            uri: lb://USER
            predicates:
              - Path=/items/**
          - id: cart
            uri: lb://USER
            predicates:
              - Path=/carts/**
          - id: order
            uri: lb://USER
            predicates:
              - Path=/orders/**
          - id: payment
            uri: lb://PAYMENT
            predicates:
              - Path=/payments/**
              - Path=/v2/toss/**
          - id: checkout
            uri: lb://PAYMENT
            predicates:
              - Path=/checkout/**
          - id: wallet
            uri: lb://PAYMENT
            predicates:
              - Path=/wallets/**
          - id: main
            uri: lb://PAYMENT
            predicates:
              - Path=/*
