eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka

server:
  port: 8080


spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: item-service
            uri: lb://ITEM-SERVICE
            predicates:
            - Path=/items/**,/carts/**,/{userId}/carts/**
          - id: user-service
            uri: lb://USER-SERVICE
            predicates:
            - Path=/users/**
          - id: payment-service
            uri: lb://PAYMENT-SERVICE
            predicates:
            - Path=/orders/**,/payments/**,/confirm/**,/checkout
          - id: wallet-service
            uri: lb://PAYMENT-SERVICE
            predicates:
            - Path=/wallets/**
          - id: main
            uri: lb://PAYMENT-SERVICE
            predicates:
            - Path=/*
logging:
  level:
    org.springframework.cloud.gateway: trace
    reactor.netty: trace
